
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AMPERSAND AND APOSTROPHE ASYNC AWAIT BOOL CATCH CLOSE COLON COMA COMMENT DIVISION DOLLAR DOT DOUBLE DOUBLEQUAL DOUBQUOTMARK DYNAMIC ELSE EQUAL EXIT EXMARK FALSE FILE FLOAT FOR GREATERTHAN IDENTIFIER IF IMPORT IN INT INTEGER IS ITERABLE LCURLYBRACKET LESSTHAN LIST LPAREN LSQUAREBRACKET MAIN METHOD MINUS NOTEQUAL OPENWRITE OR PLUS PRINT RCURLYBRACKET READLINESYNC RETURN RPAREN RSQUAREBRACKET SEMICOLON SET STR STRING TIMES TRUE TRY VAR VOID WHILE WRITEclase : INT MAIN'
    
_lr_action_items = {'INT':([0,],[2,]),'$end':([1,3,],[0,-1,]),'MAIN':([2,],[3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'clase':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> clase","S'",1,None,None,None),
  ('clase -> INT MAIN','clase',2,'p_clase','main.py',111),
]
